# Generated by Django 3.1.2 on 2022-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('S', 'Spanish')], default='E', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=1),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
